### ISSUE TITLE
Production mode / standalone jar doesn't work with Spring Boot

### ISSUE THREAD

**Issue by mosi0815** [devsoap/gradle-vaadin-flow#142]
The easiest way to reproduce the error is to check out: 
https://github.com/devsoap/examples/tree/master/flow-spring-tutorial

After setting producitonMode to true in application.properties and build.gradle the following output it produced when opening the application in a browser:

> Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.

When started as standalone jar via java -jar in development mode this message is shown:

> There was an exception while trying to navigate to '' with the exception message 'Error creating bean with name 'org.vaadin.spring.tutorial.RootComponent': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exampleTemplate' defined in URL [jar:file:/home/ralph/tmp/examples/flow-spring-tutorial/build/libs/flow.tutorial.jar!/BOOT-INF/classes!/org/vaadin/spring/tutorial/ExampleTemplate.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.vaadin.spring.tutorial.ExampleTemplate]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Can't find resource 'frontend://ExampleTemplate.html' via the servlet context'

The only way to get it working is to use the bootRun task or to run it via IntelliJ.

As far as I can see the static resources are in the wrong folders inside the jar. In exploded mode it somehow works.

**Comment by johndevs** [comment]
Could be related to a bug in how Vaadin handles frontend resources https://github.com/vaadin/flow/issues/3600. Could you verify with 1.2.0.alpha1 where they claim it should be fixed?

**Comment by mosi0815** [comment]
No. This makes no sense. The Vaadin starter with Spring Boot works perfectly in production mode. ( https://vaadin.com/start/latest/full-stack-spring )
I've compared the jars a little bit. The static resources are in a whole different folder. I think this is the issue. I'm not an expert how Vaadin Flow works so it's a little bit hard for me to debug.

**Comment by mosi0815** [comment]
I just tried it with the new RC3. Still doesn't work.
Did you enable production mode in application.yml and build.gradle?
When I do I get the following error:

> java.lang.IllegalStateException: Can't find resource 'frontend://ExampleTemplate.html' via the servlet context
